### PR TITLE
🐛 Fix speaker buttons showing over speakerdropdown

### LINKED ISSUE #316: Speaker buttons on hover shown above speaker dropdown

### PR DESCRIPTION
**Pull request by pajowu**
To be honest, I don't understand *why* this fixes it, but it does?

Fixes #316

### CODE REVIEW

**Comment by phlmn** [comment]
I think this re-introduces problems when the dropdown is higher than the paragraph... Then it is rendered behind the next speaker name. Maybe something like `hover:z-10` does the job?

**Comment by pajowu** [comment]
I can't replicate that (if that is what you meant?)

Screenshot 2023-07-31 at 17 42 17

Screenshot 2023-07-31 at 17 42 21

**Comment by phlmn** [comment]
Sorry, I meant the button to open the dropdown: 
image

**Comment by pajowu** [comment]
Ah, now I understand. `hover:z-10` seems to be the solution, which I now added instead

**Comment by phlmn** [comment]
It's even more cursed... I pushed a fix, but I don't like the code...

**Comment by anuejn** [comment]
so... can we merge this?

**Comment by pajowu** [comment]
IMO yes, just needs an approving review

**Review by anuejn — APPROVED** [review]

**Pull request merged**
